name: Deploy Frontend to S3
on: 
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths: 
      - 'frontend/**'
env:
  AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
permissions:
  id-token: write
  contents: read
jobs:
  S3Sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install and Build
        working-directory: ./frontend
        run: |
          npm install
          npm run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: github-action-coffee
          aws-region: ${{ env.AWS_REGION }}
      - name: Sync S3 Bucket
        working-directory: ./frontend/dist
        run: aws s3 sync . ${{ env.AWS_BUCKET_NAME }} --delete
