name: Deploy GetItem Lambda

on:
  workflow_dispatch:
  push:
    branches: 
      - 'main'
    paths:
      - 'backend/functions/getItem/**'
env:
  AWS_FUNCTION_NAME: ${{ secrets.AWS_GETITEM_FUNCTION_NAME }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
permissions:
  id-token: write
  contents: read
jobs:
  DeployGetItem:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build Go binary for Lambda (arm64)
        run: |
          cd backend/functions/getItem
          GOOS=linux GOARCH=arm64 go build -o bootstrap main.go
          zip function.zip bootstrap
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: github-action-coffee
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.AWS_FUNCTION_NAME }} \
            --zip-file fileb://backend/functions/getItem/function.zip
